// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQNGfCY8bHWqsPK66-o-Iht1xbgcpCwBo',
    appId: '1:231634933826:web:1cdfddd2c51f3ebd2a75db',
    messagingSenderId: '231634933826',
    projectId: 'pocketguide-ed5e5',
    authDomain: 'pocketguide-ed5e5.firebaseapp.com',
    storageBucket: 'pocketguide-ed5e5.appspot.com',
    measurementId: 'G-008GGMTG5R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGXxBvUHvteLYrtS8PxYlPswI80LU4FF8',
    appId: '1:231634933826:android:201141d07a0350232a75db',
    messagingSenderId: '231634933826',
    projectId: 'pocketguide-ed5e5',
    storageBucket: 'pocketguide-ed5e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoGHlT7llzDoIRKi0dUeb3bOcgWe4S_nY',
    appId: '1:231634933826:ios:e342174e24d59a4b2a75db',
    messagingSenderId: '231634933826',
    projectId: 'pocketguide-ed5e5',
    storageBucket: 'pocketguide-ed5e5.appspot.com',
    iosClientId: '231634933826-as7osrb37imbptj21rdd4q05i8g849ah.apps.googleusercontent.com',
    iosBundleId: 'com.example.pocketGuide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoGHlT7llzDoIRKi0dUeb3bOcgWe4S_nY',
    appId: '1:231634933826:ios:e342174e24d59a4b2a75db',
    messagingSenderId: '231634933826',
    projectId: 'pocketguide-ed5e5',
    storageBucket: 'pocketguide-ed5e5.appspot.com',
    iosClientId: '231634933826-as7osrb37imbptj21rdd4q05i8g849ah.apps.googleusercontent.com',
    iosBundleId: 'com.example.pocketGuide',
  );
}
